format = """
[](#a7c080)\
[󰣭 ](bg:#a7c080 fg:#3c4841)\
$username\
[](bg:#83c092 fg:#a7c080)\
$directory\
[](fg:#83c092 bg:#7a8478)\
$git_branch\
$git_status\
[](fg:#7a8478 bg:#4f5b58)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#4f5b58 bg:#495156)\
$docker_context\
[](fg:#495156 bg:#384b55)\
$time\
[ ](fg:#384B55)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#a7c080 fg:#3c4841"
style_root = "bg:#a7c080"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#a7c080"
disabled = true # Disabled by default

[directory]
style = "bg:#83c092 fg:#3c4841"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#4f5b58"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:#4f5b58"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#495156"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#4f5b58"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#4f5b58"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#7a8478"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#7a8478"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#4f5b58"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#4f5b58"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#4f5b58"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#4f5b58"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#4f5b58"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#4f5b58"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#4f5b58"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#4f5b58"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#4f5b58"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#384b55"
format = '[ 󰳭 $time ]($style)'
